### ISSUE TITLE
What is the USER name and PASSWORD of librarion and user??? How do i get it??? [Resolved]

### ISSUE THREAD

**Issue by iam-shubhamsharma** [EncoSier/DBISProject#1]
Not working....

**Comment by bikashtudu** [comment]
Read readme.md, you will find the steps for importing the database(structure+information).
Some username and password in the database are,
Librarian
Username: Encosier
Password: 1234

User
Username : Deco
Password : 1234

After logging as librarian you can see all the users(and their password)

**Comment by kdrewa** [comment]
username and   password    error

**Comment by kdrewa** [comment]
give   me   solution

**Comment by kdrewa** [comment]
i  need  to  this  project  because  next week  my   major  project  in  college

**Comment by mogovic** [comment]
the username and the password that you provided for user and librarian is not working. can you give us the correct one . thanks

**Comment by bikashtudu** [comment]
Please check the Users table in the database.
Have you imported the tables into your MySQL server? I check from the table if the User that you have entered exists in the table for not.

https://github.com/bikashtudu/DBISProject/blob/99f142b5ecf19318c57d966de8f7b96f3b122d54/src/mainlibrary/UsersDao.java#L19-L31

**Comment by SharminAkter21** [comment]
the username and the password that you provided for user and librarian is not working. can you give us the correct one . please help

**Comment by bikashtudu** [comment]
Please share screenshot of the error

**Comment by SharminAkter21** [comment]
Assalamualikum,
I have solved the problem. Could you please kindly tell me what are the
Technologies are used in this project?
