### ISSUE TITLE
password  and  username   error message  on   screen [Resolved]

### ISSUE THREAD

**Issue by kdrewa** [EncoSier/DBISProject#2]
give  me some solution   of  this  error  . please

**Comment by bikashtudu** [comment]
can you send me the error or the screenshot of it.

**Comment by kdrewa** [comment]
i have  solve problem

**Comment by kdrewa** [comment]
username and password   have accepted

**Comment by kdrewa** [comment]
thanks

**Comment by DivyaShreenidhi** [comment]
I am unable to login with user name as Encosier and password as 1234. Please tell me how resolve this error.
