### ISSUE TITLE
How to connect Database to Java? Complete steps please! [Resolved]

### ISSUE THREAD

**Issue by sauravgpt** [EncoSier/DBISProject#3]
Here there I've downloaded all the required files but don't know any steps how to connect Database to Netbeans. As it shows Incorrect Password on logic page. I need each and every steps including creating connection to running the project.

**Comment by bikashtudu** [comment]
@sauravgpt Go through the readme, I have already written all the steps to import the database(create schema+ data), and how to include the JDBC in the project. 

Regarding incorrect password, go through the [closed issues](https://github.com/bikashtudu/DBISProject/issues?q=is%3Aissue+is%3Aclosed).

**Comment by sauravgpt** [comment]
Sir I don't know how to create connection link between workbench and NetBeans

**Comment by bikashtudu** [comment]
@sauravgpt Connection between the Java application and MYSQL server is done via the APIs from the JDBC.

[DB.java](https://github.com/bikashtudu/DBISProject/blob/test/src/mainlibrary/DB.java) have all the setup for the connection. You can change it as you want accordingly.

**Comment by sauravgpt** [comment]
Bro please can you please make any tutorial video from cloning to connecting to running to adding or deleting users?

**Comment by bikashtudu** [comment]
@sauravgpt No, this is not video tutorial.
Please look at the requirements and the instructions.

As this is not build or project issue I'm closing this is not issue(As I have alreadt mentioned the requirements).
